
runtime: java
env: flex
#instance_class: F2
handlers:
 - url: /.*
   script: this field is required, but ignored
  
  
#- url: /
#  static_files: static/index.html
#  #upload: index.html
#  
#runtime_config:  # Optional
#  jdk: openjdk8
#  server: jetty9


# Explicitly set the memory limit and maximum heap size for the Spring Boot app
#env_variables:
#  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m -XX:ActiveProcessorCount=2 -Xmx32m"
# [END gae_java11_helloworld_yaml]